version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpass  # Cập nhật mật khẩu
      - MYSQL_DATABASE=app_web1
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass  # Cập nhật mật khẩu
      - MYSQL_DATABASE=app_web1
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=rootpass  # Cập nhật mật khẩu
      - PMA_PORT=3306
    ports:
      - "8082:80"
    depends_on:
      - mysql
volumes:
  mysql-data: